In [217]:
import pandas as pd

In [218]:
plantgen = pd.read_csv('/Users/noshintasnim/Downloads/Solar-Energy-Yield-Predictor/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Generation_Data.csv')
plantweather = pd.read_csv('/Users/noshintasnim/Downloads/Solar-Energy-Yield-Predictor/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Weather_Sensor_Data.csv')

In [219]:
plantgen.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15 00:00:00,4136001,4UPUqMRk7TRMgml,0.0,0.0,9425.000000,2.429011e+06
1,2020-05-15 00:00:00,4136001,81aHJ1q11NBPMrL,0.0,0.0,0.000000,1.215279e+09
2,2020-05-15 00:00:00,4136001,9kRcWv60rDACzjR,0.0,0.0,3075.333333,2.247720e+09
3,2020-05-15 00:00:00,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06
4,2020-05-15 00:00:00,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07

In [220]:
plantweather.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,iq8k7ZNt4Mwm3w0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,iq8k7ZNt4Mwm3w0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,iq8k7ZNt4Mwm3w0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,iq8k7ZNt4Mwm3w0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,iq8k7ZNt4Mwm3w0,26.596148,25.088210,0.0

In [221]:
plantgen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67698 entries, 0 to 67697
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    67698 non-null  object
 1   PLANT_ID     67698 non-null  int64
 2   SOURCE_KEY   67698 non-null  object
 3   DC_POWER     67698 non-null  float64
 4   AC_POWER     67698 non-null  float64
 5   DAILY_YIELD  67698 non-null  float64
 6   TOTAL_YIELD  67698 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.6+ MB

In [222]:
plantweather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3259 entries, 0 to 3258
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3259 non-null   object
 1   PLANT_ID             3259 non-null   int64
 2   SOURCE_KEY           3259 non-null   object
 3   AMBIENT_TEMPERATURE  3259 non-null   float64
 4   MODULE_TEMPERATURE   3259 non-null   float64
 5   IRRADIATION          3259 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 152.9+ KB

In [223]:
plantgen['DATE_TIME'] = pd.to_datetime(plantgen['DATE_TIME'], errors='coerce')
plantweather['DATE_TIME'] = pd.to_datetime(plantweather['DATE_TIME'], errors='coerce')

plantgen_agg = plantgen.groupby('DATE_TIME').agg({'PLANT_ID': 'first', 'DC_POWER': 'sum', 
                    'AC_POWER': 'sum', 'DAILY_YIELD': 'sum'}).reset_index()
plantgen_agg.head()

            DATE_TIME  PLANT_ID  DC_POWER  AC_POWER   DAILY_YIELD
0 2020-05-15 00:00:00   4136001       0.0       0.0  48899.938095
1 2020-05-15 00:15:00   4136001       0.0       0.0  28401.000000
2 2020-05-15 00:30:00   4136001       0.0       0.0  28401.000000
3 2020-05-15 00:45:00   4136001       0.0       0.0  28401.000000
4 2020-05-15 01:00:00   4136001       0.0       0.0  26516.000000

In [224]:
plantweather.drop(columns=['SOURCE_KEY'], inplace=True)
plantweather.head()

,DATE_TIME,PLANT_ID,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,26.596148,25.088210,0.0

In [225]:
plantdata = pd.merge(plantgen_agg, plantweather, on=['DATE_TIME', 'PLANT_ID'], how='left')
plantdata.head()

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,0.0,0.0,48899.938095,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,28401.000000,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,28401.000000,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,28401.000000,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,26516.000000,26.596148,25.088210,0.0

In [226]:
plantdata.insert(3, 'DCE', (plantdata['DC_POWER'] / plantdata['DC_POWER'].max()).fillna(0))
plantdata.insert(5, 'ACE', (plantdata['AC_POWER'] / plantdata['AC_POWER'].max()).fillna(0))
plantdata.insert(6, 'CE', (plantdata['AC_POWER'] / plantdata['DC_POWER'].max()).fillna(0))

In [227]:
plantdata.head(10)

,DATE_TIME,PLANT_ID,DC_POWER,DCE,AC_POWER,ACE,CE,DAILY_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,0.0,0.0,0.0,0.0,0.0,48899.938095,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,0.0,0.0,0.0,26516.000000,26.596148,25.088210,0.0
5,2020-05-15 01:15:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.512740,25.317970,0.0
6,2020-05-15 01:30:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.494339,25.217193,0.0
7,2020-05-15 01:45:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.420410,25.065062,0.0
8,2020-05-15 02:00:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.401946,24.691469,0.0
9,2020-05-15 02:15:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.226078,24.559481,0.0

In [228]:
plantdata = plantdata.rename(columns={'DCE': 'DC_EFFICIENCY', 'ACE': 'AC_EFFICIENCY', 'CE': 'CONVERSION_EFFICIENCY'})
plantdata.head(10)

,DATE_TIME,PLANT_ID,DC_POWER,DC_EFFICIENCY,AC_POWER,AC_EFFICIENCY,CONVERSION_EFFICIENCY,DAILY_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,0.0,0.0,0.0,0.0,0.0,48899.938095,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,0.0,0.0,0.0,28401.000000,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,0.0,0.0,0.0,26516.000000,26.596148,25.088210,0.0
5,2020-05-15 01:15:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.512740,25.317970,0.0
6,2020-05-15 01:30:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.494339,25.217193,0.0
7,2020-05-15 01:45:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.420410,25.065062,0.0
8,2020-05-15 02:00:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.401946,24.691469,0.0
9,2020-05-15 02:15:00,4136001,0.0,0.0,0.0,0.0,0.0,18976.000000,26.226078,24.559481,0.0

In [229]:
plantdata.to_csv('SOLAR_PLANT_DATA(GENERATION_AND_WEATHER).csv', index=False)